### ISSUE TITLE
Conflict between sniffs in a multi-line function call

### ISSUE THREAD

**Issue by angelsk** [leaphub/phpcs-symfony2-standard#6]
I raised this here https://github.com/squizlabs/PHP_CodeSniffer/issues/788 - but probably more relevant here.

So I updated https://github.com/squizlabs/PHP_CodeSniffer to 2.4.0 and ran the code sniffer against your Symfony 2 coding standards.  
` bin/phpcs --standard=vendor/leaphub/phpcs-symfony2-standard/leaphub/phpcs/Symfony2/ --extensions=php src/`

I got the following error:

`Empty lines are not allowed in multi-line function calls`

I removed the empty lines.

I re-ran.

I got the following error:

`Missing blank line before return statement conflict`

And got stuck in a loop.

Here is (one of) the offending code snippet(s)

```
$lastListing = ['document' => ['versionNumber' => '']];
$itemListing = array_filter($itemListing, function ($item) use (&$lastListing) {
    $dupeItem = $item;
    unset($dupeItem['document']['versionNumber']);
    $dupeItem2 = $lastListing;
    unset($dupeItem2['document']['versionNumber']);
    $lastListing = $item; // For next compare

    return $dupeItem != $dupeItem2;
});
```

Ran with -s to get the sniffs

- Missing blank line before return statement - (Symfony2.Formatting.BlankLineBeforeReturn)
- Empty lines are not allowed in multi-line function calls - (PEAR.Functions.FunctionCallSignature.EmptyLine)

**Comment by cfoehrdes** [comment]
Thanks for reporting this! We are expecting the same problem since our dependency update. Will try to fix it in the next days.

**Comment by angelsk** [comment]
Hi, not wanting to bug - but any update on this?

**Comment by angelsk** [comment]
This doesn't seem to occur any more.
