### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by staegi** [leaphub/phpcs-symfony2-standard#9]
I get a bunch of deprecation warnings:

`bin/phpcs --standard=vendor/leaphub/phpcs-symfony2-standard/leaphub/phpcs/Symfony2 --extensions=php app src tests`

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 2028

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 2033

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 2033

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 2079

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 2079

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php on line 386

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php on line 389

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php on line 431

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php on line 434

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PEAR/Sniffs/Commenting/InlineCommentSniff.php on line 59

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PEAR/Sniffs/Commenting/InlineCommentSniff.php on line 70

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PEAR/Sniffs/Commenting/InlineCommentSniff.php on line 71

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PEAR/Sniffs/Commenting/InlineCommentSniff.php on line 74

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PEAR/Sniffs/Commenting/InlineCommentSniff.php on line 75

**Comment by cfoehrdes** [comment]
Hi @staegi, I will mark this package as discontinued and add a recommendation to switch to https://github.com/slevomat/coding-standard which we are using now as a basis for our own standard.

We developed this one in times of Symfony 2 and are not longer using/maintaining it.
